name: street_sprint_flutter
description: A colorful endless runner mobile game
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flame: 1.16.0
  flame_audio: ^2.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  google_mobile_ads: ^5.0.0
  in_app_purchase: ^3.1.13
  cupertino_icons: ^1.0.6
  audioplayers: ^5.2.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/music/
    - assets/audio/sfx/
